name: Generate website

on:
  push:
    branches:
      - main
    paths:
      - '.github/actions/build-setup/**/*'
      - '.github/workflows/generate-website.yml'
      - '.nvmrc'
      - 'packages/core/**/*'
      - 'packages/website/**/*'
      - '!packages/website/README.md'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
  # Allows you to deploy manually to GH Pages from the Actions tab (only if run from the main branch)
  workflow_dispatch:

  pull_request:
    branches:
      - main
    paths:
      - '.github/actions/build-setup/**/*'
      - '.github/workflows/generate-website.yml'
      - '.nvmrc'
      - 'packages/core/**/*'
      - 'packages/html/**/*'
      - '!packages/html/README.md'
      - 'packages/website/**/*'
      - '!packages/website/README.md'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'


# Allow one concurrent deployment
# Use a dynamic name to run the workflow in parallel for the build part (in particular in PRs)
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read
    uses: ./.github/workflows/_reusable_generate_website.yml
    with:
      artifact-name: ${{ github.event_name == 'pull_request' && format('website-pr-{0}-{1}', github.event.pull_request.number, github.sha) || 'gh-pages' }}

  deploy:
    needs: build
    if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: read
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
